### ISSUE TITLE
Binary for Windows

### ISSUE THREAD

**Issue by caifazhou** [strohel/PyBayes#15]
Anyone try to install on  windows? I got an error:

`
Collecting PyBayes
  Using cached https://files.pythonhosted.org/packages/e5/12/84e4ffaf167968c824a5cf2c9e1b5edaf6c0c9f920c93cb8cc4337f7cbbd/PyBayes-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\czhou\AppData\Local\Temp\pip-install-zqvu4hb6\PyBayes\setup.py", line 23
        print "Failed to determine version using git:", e
                                                     ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to determine version using git:", e)?
`

**Comment by strohel** [comment]
Hi, this seems to be caused by the fact that setup.py is still written for Python 2.7, you seem to be installing under Python 3.x. Should be easy to fix (make it run under both), care to submit a PR?
